### PR TITLE
Create testworkflow.yml

### PR DESCRIPTION
**Pull request by graceochie**
CI workflow to build and push our docker image.

### CODE REVIEW

**Review by Bethel-tech — COMMENTED** [review]
Remove on event and change it to on schedule instead of on push and PR. 
Change the run for step 1 to run the dockerfile instead of building with a new name tag.

**Review by Bethel-tech — CHANGES_REQUESTED** [review]
Remove on event and change it to on schedule instead of on push and PR.
Change the run for step 1 to run the dockerfile instead of building with a new name tag.

**Review by Bethel-tech — APPROVED** [review]
Changes made.

**Review by Bethel-tech — APPROVED** [review]

**Review by graceochie — COMMENTED** [review]
changes made

**Review by Bethel-tech — APPROVED** [review]
All good.

**Pull request merged**
